server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html index.htm;

    # Serve Vue frontend (fall back to index.html for SPA routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Handle PHP backend API requests routed into /api/
    location /api {
        try_files $uri $uri/ /api/index.php?$query_string;
    }

    location ~ ^/api/.+\.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000; # Connects to the php-fpm container service
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;

        # in case we're begind another reverse proxy
        real_ip_header X-Forwarded-For;
        set_real_ip_from 192.168.1.180; # next hop
        fastcgi_param REMOTE_ADDR $remote_addr;

    }
}